version: '3.4'

services:
  play_db:
    image: mysql:8.0.19
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: play_data
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  playwith.oauth:
    image: ${DOCKER_REGISTRY-}playwithoauth
    build:
      context: .
      dockerfile: PlayWith.Oauth/Dockerfile

  playwith.api:
    image: ${DOCKER_REGISTRY-}playwithapi
    build:
      context: .
      dockerfile: PlayWith.Api/Dockerfile