version: '3.4'

services:
  palywith.oauth:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  palywith.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

