version: '3.4'

services:
  playwith.oauth:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  playwith.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

