version: '3.4'

services:
  mysql.data:
    image: mysql:8.0.19
    volumes:
      - "/var/data/.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: play_data
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  playwith.oauth:
    image: ${DOCKER_REGISTRY-}playwithoauth:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: PlayWith.Oauth/Dockerfile
    depends_on:
      - mysql.data

  playwith.api:
    image: ${DOCKER_REGISTRY-}playwithapi:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: PlayWith.Api/Dockerfile

  watchtower:
    image: containrrr/watchtower
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/root/.docker/config.json:/config.json"
    environment:
      - "debug : true"
    #  REPO_USER : ${REPO_USER}
    #  REPO_PASS : ${REPO_PASS}
    command: --interval 60