name: Docker Image CI

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v2  
    
    - name: login aliyun docker registry
      run: docker login -u=${{ secrets.ALI_DOCKER_REGISTRY_USER }} -p=${{ secrets.ALI_DOCKER_REGISTRY_SECRET }} registry.cn-shenzhen.aliyuncs.com
    
    - name: build image
      run: docker-compose -f docker-compose.yml  -f docker-compose.override.yml build
      
    - name:  push image
      run: docker-compose -f docker-compose.yml  -f docker-compose.override.yml push
